[package]
name = "solar-screen-brightness"
version = "0.1.0"
authors = ["Jacob Halsey <jacob@jhalsey.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = {default-features = false, features = ["crossterm-backend"], git = "https://github.com/gyscos/cursive"}
rust-embed = "5.5.1"
config = "0.10.1"
serde = { version = "1.0.110", features = ["derive"] }


[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["consoleapi", "windef", "processthreadsapi", "errhandlingapi", "winerror", "shellapi", "libloaderapi"] }

[build-dependencies]
cmake = "0.1"
bindgen = "0.53.1"
