[package]
name = "solar-screen-brightness"
version = "0.1.0"
authors = ["Jacob Halsey <jacob@jhalsey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = {version= "0.11", default-features = false, features = ["crossterm-backend"]}

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["consoleapi", "windef", "processthreadsapi", "errhandlingapi", "winerror"] }
