[package]
name = "solar-screen-brightness-windows-bindings"
version = "0.1.0"
edition = "2018"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = "0.18.0"

[build-dependencies]
windows = "0.18.0"
